### ISSUE TITLE
Invalid block for tracing (Fantom)

### ISSUE THREAD

**Issue by canercidam** [forta-network/forta-node#556]
Looks like in some of the Fantom nodes which use the public APIs, there is an invalid block for tracing problem. This is likely because of not keeping the distance from the latest block.
```yaml
chainId: 250

scan:
  jsonRpc:
    url: https://rpc.ftm.tools/

trace:
  jsonRpc:
    url: https://rpcapi-tracing.fantom.network/
```
![unknown](https://user-images.githubusercontent.com/14118507/182824217-08f1d542-b71c-4d84-b78f-dd2c5f4420c0.png)
